name: presence_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.7.1
  get: 4.6.1
  firebase_core: 1.14.0
  firebase_auth: 3.3.12
  cloud_firestore: 3.1.11
  firebase_storage: 10.2.10
  image_picker: 0.8.5
  convex_bottom_bar: 3.0.0
  intl: 0.17.0
  geolocator: 8.2.0
  geocoding: 2.0.4
  google_fonts: 2.3.1
  syncfusion_flutter_datepicker: 20.1.47
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

