// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4YMfapjTM1N2O01zzyannAnKMvZaDFwU',
    appId: '1:189703809317:android:da3ddabe7ea80fd0af92cc',
    messagingSenderId: '189703809317',
    projectId: 'presence-3a8d1',
    storageBucket: 'presence-3a8d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGLjUIr-iG-W3shOJPIIJCC67Uir3_DHw',
    appId: '1:189703809317:ios:1f65bcb40848553baf92cc',
    messagingSenderId: '189703809317',
    projectId: 'presence-3a8d1',
    storageBucket: 'presence-3a8d1.appspot.com',
    iosClientId: '189703809317-lbdqrvq84d9d1um23mpgbr7a4i27rmvi.apps.googleusercontent.com',
    iosBundleId: 'com.alwirosproject.presence',
  );
}
